name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "VITE_API_URL=http://${{ secrets.EC2_HOST }}:3000" > .env

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          # 🚨 ESTA LÍNEA ES VITAL PARA AMAZON LINUX 2023 🚨
          algorithms: ssh-rsa
          script: |
            # 1. SOLUCIÓN AL ERROR DE PERMISOS
            sudo chmod 666 /var/run/docker.sock

            # 2. INSTALACIÓN DE DOCKER COMPOSE
            if ! command -v docker-compose &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
              sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose || true
            fi

            # 3. Login en Docker Hub
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            # 4. Pull de la imagen
            docker pull ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest

            # 5. Crear archivo docker-compose.yml
            cat <<EOF > docker-compose-frontend.yml
            services:
              frontend:
                image: ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest
                container_name: frontend
                restart: always
                ports:
                  - "80:80"
            EOF

            # 6. Limpieza y Despliegue
            docker-compose -f docker-compose-frontend.yml down || true
            docker-compose -f docker-compose-frontend.yml up -d
            
            # Limpiar imágenes antiguas para no llenar el disco
            docker image prune -f
